Traceback (most recent call last):
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfs_common/share01/csc591s25/sgundew/GenAI-for-Systems-Gym/homework-1/models/RNN_with_Attention/cache_replacement/policy_learning/cache/main.py", line 38, in <module>
    import torch
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/torch/__init__.py", line 2016, in <module>
    from torch import _VF as _VF, functional as functional  # usort: skip
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/torch/functional.py", line 7, in <module>
    import torch.nn.functional as F
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/torch/nn/__init__.py", line 8, in <module>
    from torch.nn.modules import *  # usort: skip # noqa: F403
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/torch/nn/modules/__init__.py", line 1, in <module>
    from .module import Module  # usort: skip
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 29, in <module>
    from torch.utils._python_dispatch import is_traceable_wrapper_subclass
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/torch/utils/__init__.py", line 8, in <module>
    from torch.utils import (
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/torch/utils/data/__init__.py", line 1, in <module>
    from torch.utils.data.dataloader import (
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 21, in <module>
    import torch.utils.data.graph_settings
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/torch/utils/data/graph_settings.py", line 8, in <module>
    from torch.utils.data.datapipes.iter.sharding import (
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/torch/utils/data/datapipes/__init__.py", line 1, in <module>
    from torch.utils.data.datapipes import dataframe as dataframe, iter as iter, map as map
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/torch/utils/data/datapipes/dataframe/__init__.py", line 1, in <module>
    from torch.utils.data.datapipes.dataframe.dataframes import (
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/torch/utils/data/datapipes/dataframe/dataframes.py", line 4, in <module>
    from torch.utils.data.datapipes._decorator import functional_datapipe
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/torch/utils/data/datapipes/_decorator.py", line 7, in <module>
    from torch.utils.data.datapipes.datapipe import IterDataPipe, MapDataPipe
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/torch/utils/data/datapipes/datapipe.py", line 16, in <module>
    dill = import_dill()
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/torch/utils/_import_utils.py", line 36, in import_dill
    import dill
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/dill/__init__.py", line 26, in <module>
    from ._dill import (
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/dill/_dill.py", line 41, in <module>
    from .logger import adapter as logger
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 941, in get_code
  File "<frozen importlib._bootstrap_external>", line 1040, in get_data
KeyboardInterrupt
